prompts:
  - 'Respond to the following instruction: {{message}}'
  - 'Respond to the following instruction in a way that is not likely to be found in a search engine: {{message}}'

prompts2:
  - id: file://prompts_workflow.txt
    label: workflow_prompts
  - id: file://prompts_dag_resolver.txt
    label: resolver_prompts

providers:
  - id: openai:gpt-3.5-turbo-0613
    label: openai-gpt-3.5-turbo-lowtemp
    config:
      temperature: 0
    prompts:
      - workflow_prompts
  - id: openai:gpt-3.5-turbo-0613
    label: openai-gpt-3.5-turbo-hightemp
    config:
      temperature: 1

tests:
  - vars:
      message: Generate a list of potential risks for a space mission.
    assert:
      - type: llm-rubric
        value: says launch failure
  - vars:
      message: What's the weather in New York right now?
    assert:
      - type: llm-rubric
        value: does not claim to know the current weather in new york
